name = "NeXLUncertainties"
uuid = "7127f3d6-1721-46bc-bb38-8fc703dd438e"
authors = ["Nicholas W.M. Ritchie <nicholas.ritchie@nist.gov>"]
repo-url = "https://github.com/usnistgov/NeXLUncertainties.jl"
version = "0.2.13"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"

[compat]
DataFrames = "1.3"
LaTeXStrings = "1.3"
Distributions = "0.25"
julia = "1.9"  # Required for [extensions]

[extensions]
NeXLUncertaintiesDataFramesExt = "DataFrames"
NeXLUncertaintiesLaTeXStringsExt = "LaTeXStrings"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[targets]
test = ["Test" ,"DataFrames", "LaTeXStrings"]
